name: galacticpawsweb
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
     sdk: flutter
  jaspr: ^0.15.1
  jaspr_flutter_embed: ^0.3.4
  jaspr_router: ^0.5.1

  cupertino_icons: ^1.0.6
  image_sequence_animator: ^2.0.0
  flutter_map: ^7.0.2
  url_launcher: ^6.3.0

  latlong2: any
#  jaspr: ^0.15.1

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.10
  jaspr_builder: ^0.15.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  jaspr_lints: ^0.1.1

dependency_overrides:
  meta: ^1.15.0
  analyzer: ^6.5.0

jaspr:
  mode: server

flutter:
  uses-material-design: true
